# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'agenda.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(281, 406)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.saveButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveButton.setGeometry(QtCore.QRect(110, 120, 75, 23))
        self.saveButton.setObjectName("saveButton")
        self.nomeLine = QtWidgets.QLineEdit(self.centralwidget)
        self.nomeLine.setGeometry(QtCore.QRect(80, 20, 191, 20))
        self.nomeLine.setObjectName("nomeLine")
        self.telLine = QtWidgets.QLineEdit(self.centralwidget)
        self.telLine.setGeometry(QtCore.QRect(80, 50, 191, 20))
        self.telLine.setObjectName("telLine")
        self.emailLine = QtWidgets.QLineEdit(self.centralwidget)
        self.emailLine.setGeometry(QtCore.QRect(80, 80, 191, 20))
        self.emailLine.setObjectName("emailLine")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 20, 47, 13))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 80, 47, 13))
        self.label_3.setObjectName("label_3")
        self.tableView = QtWidgets.QTableWidget(self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(10, 150, 261, 192))
        self.tableView.setObjectName("tableWidget")
        self.tableView.setColumnCount(0)
        self.tableView.setRowCount(0)
        #self.tableView.setDisabled(True)
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(30, 350, 225, 23))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.novoBtn = QtWidgets.QPushButton(self.splitter)
        self.novoBtn.setObjectName("novoBtn")
        self.editarBtn = QtWidgets.QPushButton(self.splitter)
        self.editarBtn.setObjectName("editarBtn")
        self.excluirBtn = QtWidgets.QPushButton(self.splitter)
        self.excluirBtn.setObjectName("excluirBtn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Agenda"))
        self.saveButton.setText(_translate("MainWindow", "Salvar"))
        self.label.setText(_translate("MainWindow", "Nome: "))
        self.label_2.setText(_translate("MainWindow", "Telefone:"))
        self.label_3.setText(_translate("MainWindow", "E-mail: "))
        self.novoBtn.setText(_translate("MainWindow", "Novo"))
        self.editarBtn.setText(_translate("MainWindow", "Editar"))
        self.excluirBtn.setText(_translate("MainWindow", "Excluir"))
